name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 3.2.0

homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.4
  meta: ^1.9.1
  http_multi_server: ^3.2.1
